export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as Classes} from './Classes'
export {default as ClassDetail} from './ClassDetail'
export {default as NewClass} from './NewClass'
export {default as Profile} from './Profile'
export {default as NotFound} from './NotFound'